# work_dir: /home/yuchunli/git/training_extensions/logs/vitens_tiling_exp_mae%
work_dir: /home/yuchunli/git/training_extensions/logs/vitens_tiling_exp
env_root: /home/yuchunli/git/training_extensions/external/model-preparation-algorithm

seeds: [1, 10, 100, 1234, 4321]
template: external/model-preparation-algorithm/configs/instance-segmentation/efficientnetb2b_maskrcnn/template.yaml
params:
  - "--tiling_parameters.enable_tiling 1"
  - "--tiling_parameters.enable_adaptive_params 1"

datasets:
  Vitens-Aeromonas-coco:
    img_root: /home/yuchunli/_DATASET/Vitens-Aeromonas-coco/images
    anno_root: /home/yuchunli/_DATASET/vitens_dataset_harim/Vitens-Aeromonas-coco/annotations
    annotations_train: instances_train.json
    annotations_val: instances_val.json
    annotations_test: instances_test.json
    images_train_dir: train
    images_val_dir: val
    images_test_dir: test
    num_samples: [12, 24, 36]

  Vitens-Coliform-coco:
    img_root: /home/yuchunli/_DATASET/Vitens-Coliform-coco/images
    anno_root: /home/yuchunli/_DATASET/vitens_dataset_harim/Vitens-Coliform-coco/annotations
    annotations_train: instances_train.json
    annotations_val: instances_val.json
    annotations_test: instances_test.json
    images_train_dir: train
    images_val_dir: val
    images_test_dir: test
    num_samples: [12, 24, 36]

  Vitens-Enterococci-coco:
    img_root: /home/yuchunli/_DATASET/Vitens-Enterococci-coco/images
    anno_root: /home/yuchunli/_DATASET/vitens_dataset_harim/Vitens-Enterococci-coco/annotations
    annotations_train: instances_train.json
    annotations_val: instances_val.json
    annotations_test: instances_test.json
    images_train_dir: train
    images_val_dir: val
    images_test_dir: test
    num_samples: [12, 24, 36]

  Vitens-Legionella-coco:
    img_root: /home/yuchunli/_DATASET/Vitens-Legionella-coco/images
    anno_root: /home/yuchunli/_DATASET/vitens_dataset_harim/Vitens-Legionella-coco/annotations
    annotations_train: instances_train.json
    annotations_val: instances_val.json
    annotations_test: instances_test.json
    images_train_dir: train
    images_val_dir: val
    images_test_dir: test
    num_samples: [12, 24, 32]
