_base_: [
    # '../../venv/lib/python3.8/site-packages/recipes/stages/_base_/default.py',
    './_base_/default.py',
    '../../venv/lib/python3.8/site-packages/recipes/stages/_base_/logs/tensorboard_logger.py',
    '../../venv/lib/python3.8/site-packages/recipes/stages/_base_/optimizers/lars.py',
    '../../venv/lib/python3.8/site-packages/recipes/stages/_base_/runners/iter_runner.py',
    '../../venv/lib/python3.8/site-packages/recipes/stages/_base_/schedules/cos_anneal.py',
    # '../../venv/lib/python3.8/site-packages/recipes/stages/_base_/models/cls_selfsl.py',
    # '../../venv/lib/python3.8/site-packages/recipes/stages/_base_/data/selfsl_dataset_bs128.py'
    '../../configs/base/data/selfsl_dataset_bs128.py'
]

model:
   base_momentum: 0.97

optimizer:
    lr: 0.45
    weight_decay: 1.e-6
    mode: selfsl
    exclude_bn_from_weight_decay: true

lr_config:
    warmup: linear
    warmup_iters: 50
    warmup_ratio: 0.0001
    warmup_by_epoch: false

runner:
    max_iters: 5000

checkpoint_config:
    by_epoch: false
    interval: 10
    max_keep_ckpts: 1

log_config:
    interval: 1
    ignore_last: false

seed: 1234
deterministic: true
