_base_: [
    '../../adapters/mmcls/data/twocrop_data.py',
    './model_selfsl.py'
]

log_level: INFO

log_config:
    interval: 100
    hooks:
      - type: TextLoggerHook
        ignore_last: false
      - type: TensorboardLoggerHook

workflow:
- !!python/tuple
  - train
  - 1

runner:
    max_epochs: 20
    type: EpochRunnerWithCancel

optimizer_config:
    type: SAMOptimizerHook
    grad_clip: null

optimizer:
    type: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

lr_config:
    policy: CosineAnnealing
    min_lr_ratio: 0.0001

evaluation:
    metric: ['accuracy', 'class_accuracy']

