# Description.
model_template_id: Custom_Image_Classification_EfficientNet-V2-S
name: EfficientNet-V2-S
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Image Classification for EfficientNet-V2-S
application: ~

# Algo backend.
framework: OTEClassification v1.2.3

# Task implementations.
entrypoints:
  base: otx.algorithms.classification.tasks.ClassificationTrainTask
  openvino: otx.algorithms.classification.tasks.ClassificationOpenVINOTask
  nncf: otx.algorithms.classification.tasks.nncf.OTXClassificationNNCFTask
# base_model_path: ../../adapters/deep_object_reid/configs/efficientnet_v2_s/template_experimental.yaml

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 256
        auto_hpo_state: POSSIBLE
      num_workers:
        default_value: 0
      learning_rate:
        default_value: 0.45
        auto_hpo_state: POSSIBLE
      learning_rate_warmup_iters:
        default_value: 50
      num_iters:
        default_value: 5000
      enable_early_stopping:
        default_value: false
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      pruning_supported:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0
    algo_backend:
      train_type:
        default_value: SELFSUPERVISED

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 5.76
size: 20.23
