# Description.
model_template_id: otx_visual_prompting_lightning_sam
name: Lightning-SAM
task_type: VISUAL_PROMPTING
task_family: VISION
instantiation: "CLASS"
summary: This model is faster and in many cases more accurate, but it requires a fixed position of the objects within the image.
application: ~

# Algo backend.
framework: OTXVisualPrompting v0.1.0

# Task implementations.
entrypoints:
  base: otx.algorithms.visual_prompting.tasks.TrainingTask

# Hyper Parameters
hyper_parameters:
  base_path: ./configuration.yaml

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Computational Complexity
gigaflops: 3.9
size: 168.4
