dataset:
  description: Dataset Parameters
  header: Dataset Parameters
  num_workers:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 8
    description:
      Increasing this value might improve training speed however it might
      cause out of memory errors. If the number of workers is set to zero, data loading
      will happen in the main training thread.
    editable: true
    header: Number of workers
    max_value: 36
    min_value: 0
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: true
description: Configuration for an anomaly classification task
header: Configuration for an anomaly classification task
learning_parameters:
  description: Learning Parameters
  feature_scaling_method:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: scale
    description:
      Feature scaling method applied to the collection of extracted features
      before applying KDE.
    editable: true
    enum_name: FeatureScalingMethod
    header: Feature scaling Method
    options:
      NORM: norm
      SCALE: scale
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  header: Learning Parameters
  iou_threshold:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 0.3
    description:
      Intersection-Over-Union threshold used in class-agnostic NMS when
      post-processing the raw region proposals.
    editable: true
    header: IOU threshold
    max_value: 1
    min_value: 1.0e-05
    type: FLOAT
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  max_detections_per_image:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 100
    description:
      Maximum number of region proposals per image. Region proposals are
      included/excluded based on  class/objectness score.
    editable: true
    header: Max detections per image
    max_value: 1000
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  n_pca_components:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 16
    description:
      Number of principal components used for dimensionality reduction
      during pre-processing before training the KDE model.
    editable: true
    header: Number of PCA components.
    max_value: 128
    min_value: 2
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  roi_score_threshold:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 0.009
    description: Confidence score threshold for the region proposals.
    editable: true
    header: ROI score threshold
    max_value: 1
    min_value: 1.0e-05
    type: FLOAT
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  roi_stage:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: rcnn
    description: Processing stage of the region extractor that yields the box proposals.
    editable: true
    enum_name: ROIStage
    header: ROI stage
    options:
      RCNN: rcnn
      RPN: rpn
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  train_batch_size:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 32
    description:
      The number of training samples seen in each iteration of training.
      Increasing this value improves training time and may make the training more
      stable. A larger batch size has higher memory requirements.
    editable: true
    header: Batch size
    max_value: 512
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning:
      Increasing this value may cause the system to use more memory than available,
      potentially causing out of memory errors, please update with caution.
  type: PARAMETER_GROUP
  visible_in_ui: true
nncf_optimization:
  description: Optimization by NNCF
  enable_pruning:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: false
    description: Enable filter pruning algorithm
    editable: true
    header: Enable filter pruning algorithm
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  enable_quantization:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: true
    description: Enable quantization algorithm
    editable: true
    header: Enable quantization algorithm
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  header: Optimization by NNCF
  pruning_supported:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: false
    description: Whether filter pruning is supported
    editable: true
    header: Whether filter pruning is supported
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: true
pot_parameters:
  description: POT Parameters
  header: POT Parameters
  preset:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: Performance
    description: Quantization preset that defines quantization scheme
    editable: true
    enum_name: POTQuantizationPreset
    header: Preset
    options:
      MIXED: Mixed
      PERFORMANCE: Performance
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  stat_subset_size:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 300
    description: Number of data samples used for post-training optimization
    editable: true
    header: Number of data samples
    max_value: 9223372036854775807
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: false
type: CONFIGURABLE_PARAMETERS
visible_in_ui: true
