dataset:
  name: wgisd
  path: dataset/det_data/data/wgisd_coco
  task: visual prompting
  use_mask: false # if using mask as-is (true) or converting it to polygon (false)
  use_prompt: true # if using prompt in dataset (true) or generating random one (false)
  train_batch_size: 2
  val_batch_size: 1
  test_batch_size: 1
  num_workers: 4
  image_size: 1024 # dimensions to which images are resized (mandatory)
  transforms:
    train: null
    val: null
    test: null
  
model:
  name: SAM
  image_size: 1024
  mask_threshold: 0.
  return_logits: false
  image_encoder:
    backbone:
      name: vit_b
      patch_size: 16
      depth: 12
      embed_dim: 768
      mlp_ratio: 4
      num_heads: 12
      qkv_bias: true
      use_rel_pos: true
      global_attn_indexes:
      - 2
      - 5
      - 8
      - 11
      window_size: 14
    freeze: true
  prompt_encoder:
    prompt_embed_dim: 256
    mask_in_chans: 16
    freeze: true
  mask_decoder:
    num_multimask_outputs: 3
    transformer_cfg:
      depth: 2
      mlp_dim: 2048
      num_heads: 8
    iou_head_depth: 3
    iou_head_hidden_dim: 256
    freeze: false
  checkpoint: https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth

callback:
  checkpoint:
    # arguments for ModelCheckpoint
    monitor: val_IoU
    mode: max
    save_last: true
    verbose: true
  early_stopping:
    # arguments for EarlyStopping
    monitor: val_IoU
    mode: max
    verbose: true

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 10
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  