name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - es/check_gitmodule_test
    workflow_dispatch: # run on request (no need for PR)
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

# This is what will cancel the workflow concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs: 
  Check-Submodule:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: cat gitmodule
        id: gitmodule
        run: cat .gitmodules | grep model-preparation-algorithm)
      - name: check gitmodule
        run: if [[ "${{steps.gitmodule.conclusion}}" != "failure" ]]; then exit 1; else exit 0; fi
